"""
train_features.py — KAYABASA Features-Only Training (Ablation Configs A & B)
=============================================================================
Trains and evaluates a Random Forest classifier on the 14 handcrafted
linguistic features defined in the thesis (Table VII).

Implements two ablation configurations (§3.3.2, Table XII):
  Config A — Features only on NOISY (raw) text     → baseline
  Config B — Features only on DENOISED (clean) text → measures denoising impact

Evaluation:
  • Stratified 5-Fold Cross-Validation on high-resource languages
    (Tagalog, Cebuano, Bikolano) using the pre-saved fold_indices.pkl
  • Per-fold and mean ± std Macro-F1, Accuracy, per-class F1
  • Normalized confusion matrix (averaged across folds)

Outputs (written to output/):
  results_config_A.json  — per-fold metrics, config A (noisy features)
  results_config_B.json  — per-fold metrics, config B (denoised features)
  summary_features.txt   — human-readable comparison table

Run:
  cd feature-pipeline
  python train_features.py
"""

from __future__ import annotations

import json
import os
import pickle
import sys

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.preprocessing import LabelEncoder

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_HERE      = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.join(_HERE, "..", "data-cleaning-repo-main")

# Config B: denoised corpus (normalized)
DENOISED_CORPUS = os.path.join(_REPO_ROOT, "output_normalized", "all_languages.txt")

# Config A: noisy corpus (raw, pre-cleaning)
NOISY_CORPUS    = os.path.join(_REPO_ROOT, "output", "all_languages_raw.txt")

# Fold splits (already generated by split_datasets.py)
FOLD_PKL        = os.path.join(_REPO_ROOT, "splits", "fold_indices.pkl")
HR_INDEX_CSV    = os.path.join(_REPO_ROOT, "splits", "high_resource_index.csv")

OUTPUT_DIR      = os.path.join(_HERE, "output")

# ---------------------------------------------------------------------------
# SEED — must match split_datasets.py
# ---------------------------------------------------------------------------
SEED = 42
np.random.seed(SEED)

# ---------------------------------------------------------------------------
# Feature pipeline import
# ---------------------------------------------------------------------------
sys.path.insert(0, _HERE)
from feature_pipeline import FeaturePipeline, FEATURE_COLS, load_corpus


# ===========================================================================
# Helpers
# ===========================================================================

def _extract(corpus_path: str, label: str) -> pd.DataFrame:
    """Load corpus, extract 14 features, return DataFrame."""
    print(f"\n[{label}] Loading corpus: {corpus_path}")
    df = load_corpus(corpus_path)
    print(f"  {len(df)} docs · {df['language'].nunique()} languages")
    pipe = FeaturePipeline()
    print(f"  Extracting {len(FEATURE_COLS)} features...")
    X = pipe.fit_transform(df)
    return X


def _run_cv(
    X_full: pd.DataFrame,
    fold_indices: list,
    hr_index: pd.DataFrame,
    config_name: str,
) -> dict:
    """
    Run 5-fold CV on the high-resource subset.

    fold_indices[i] has keys 'train' and 'val': positional indices into hr_index.
    hr_index maps position → doc_id.
    X_full is keyed by doc_id.
    """
    print(f"\n{'='*60}")
    print(f"  Config {config_name} — 5-Fold CV")
    print(f"{'='*60}")

    # Build a doc_id→feature lookup from the high-resource rows only
    X_hr = (
        X_full[X_full["split_role"] == "high_resource"]
        .set_index("doc_id")
    )

    # Ensure label encoding is consistent: 1→0, 2→1, 3→2
    le = LabelEncoder()
    le.fit([1, 2, 3])

    fold_results = []
    all_y_true, all_y_pred = [], []

    for fold_num, splits in enumerate(fold_indices, start=1):
        train_pos = splits["train"]
        val_pos   = splits["val"]

        train_doc_ids = hr_index.loc[train_pos, "doc_id"].values
        val_doc_ids   = hr_index.loc[val_pos,   "doc_id"].values

        X_train = X_hr.loc[train_doc_ids, FEATURE_COLS].values
        y_train = le.transform(X_hr.loc[train_doc_ids, "label"].values)

        X_val   = X_hr.loc[val_doc_ids,   FEATURE_COLS].values
        y_val   = le.transform(X_hr.loc[val_doc_ids,   "label"].values)

        # ── Train Random Forest ───────────────────────────────────────────
        rf = RandomForestClassifier(
            n_estimators=200,
            max_depth=None,
            min_samples_leaf=2,
            class_weight="balanced",   # handles class imbalance
            random_state=SEED,
            n_jobs=-1,
        )
        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_val)

        all_y_true.extend(y_val.tolist())
        all_y_pred.extend(y_pred.tolist())

        # ── Per-fold metrics ──────────────────────────────────────────────
        acc   = accuracy_score(y_val, y_pred)
        macro = f1_score(y_val, y_pred, average="macro", zero_division=0)
        per_class_f1  = f1_score(y_val, y_pred, average=None,
                                  labels=[0,1,2], zero_division=0).tolist()
        per_class_pre = precision_score(y_val, y_pred, average=None,
                                         labels=[0,1,2], zero_division=0).tolist()
        per_class_rec = recall_score(y_val, y_pred, average=None,
                                      labels=[0,1,2], zero_division=0).tolist()

        fold_results.append({
            "fold":           fold_num,
            "n_train":        len(y_train),
            "n_val":          len(y_val),
            "accuracy":       round(acc,   4),
            "macro_f1":       round(macro, 4),
            "f1_L1":          round(per_class_f1[0], 4),
            "f1_L2":          round(per_class_f1[1], 4),
            "f1_L3":          round(per_class_f1[2], 4),
            "precision_L1":   round(per_class_pre[0], 4),
            "precision_L2":   round(per_class_pre[1], 4),
            "precision_L3":   round(per_class_pre[2], 4),
            "recall_L1":      round(per_class_rec[0], 4),
            "recall_L2":      round(per_class_rec[1], 4),
            "recall_L3":      round(per_class_rec[2], 4),
        })

        print(
            f"  Fold {fold_num}: Acc={acc:.4f}  Macro-F1={macro:.4f}"
            f"  [L1={per_class_f1[0]:.3f} L2={per_class_f1[1]:.3f}"
            f" L3={per_class_f1[2]:.3f}]"
        )

    # ── Aggregate ─────────────────────────────────────────────────────────
    macro_vals = [r["macro_f1"] for r in fold_results]
    acc_vals   = [r["accuracy"] for r in fold_results]

    mean_macro = float(np.mean(macro_vals))
    std_macro  = float(np.std(macro_vals))
    mean_acc   = float(np.mean(acc_vals))
    std_acc    = float(np.std(acc_vals))

    print(f"\n  {'-'*40}")

    print(f"  Mean Macro-F1 : {mean_macro:.4f} +/- {std_macro:.4f}")
    print(f"  Mean Accuracy : {mean_acc:.4f}   +/- {std_acc:.4f}")


    # Aggregate confusion matrix (sum across folds, then normalize)
    cm = confusion_matrix(all_y_true, all_y_pred, labels=[0, 1, 2])
    cm_norm = (cm.astype(float) / cm.sum(axis=1, keepdims=True)).round(4).tolist()

    # Per-language breakdown on the full validation predictions
    # (collect y_true, y_pred, language for all val docs across all folds)
    lang_breakdown = _per_language_breakdown(
        X_hr, fold_indices, hr_index, le, config_name
    )

    return {
        "config":           config_name,
        "folds":            fold_results,
        "mean_macro_f1":    round(mean_macro, 4),
        "std_macro_f1":     round(std_macro,  4),
        "mean_accuracy":    round(mean_acc,   4),
        "std_accuracy":     round(std_acc,    4),
        "confusion_matrix": cm_norm,
        "per_language":     lang_breakdown,
    }


def _per_language_breakdown(
    X_hr: pd.DataFrame,
    fold_indices: list,
    hr_index: pd.DataFrame,
    le: LabelEncoder,
    config_name: str,
) -> dict:
    """Macro-F1 broken down by language across all folds."""
    # Collect all OOF predictions with language labels
    records = []
    for splits in fold_indices:
        train_pos = splits["train"]
        val_pos   = splits["val"]

        train_doc_ids = hr_index.loc[train_pos, "doc_id"].values
        val_doc_ids   = hr_index.loc[val_pos,   "doc_id"].values

        X_train = X_hr.loc[train_doc_ids, FEATURE_COLS].values
        y_train = le.transform(X_hr.loc[train_doc_ids, "label"].values)

        rf = RandomForestClassifier(
            n_estimators=200, max_depth=None, min_samples_leaf=2,
            class_weight="balanced", random_state=SEED, n_jobs=-1,
        )
        rf.fit(X_train, y_train)
        y_pred = rf.predict(X_hr.loc[val_doc_ids, FEATURE_COLS].values)

        for doc_id, pred in zip(val_doc_ids, y_pred):
            records.append({
                "doc_id":   doc_id,
                "language": X_hr.loc[doc_id, "language"],
                "y_true":   le.transform([X_hr.loc[doc_id, "label"]])[0],
                "y_pred":   pred,
            })

    df_oof = pd.DataFrame(records)
    result = {}
    for lang, grp in df_oof.groupby("language"):
        macro = f1_score(grp["y_true"], grp["y_pred"],
                         average="macro", zero_division=0)
        acc   = accuracy_score(grp["y_true"], grp["y_pred"])
        result[lang] = {
            "n_docs":    len(grp),
            "macro_f1":  round(float(macro), 4),
            "accuracy":  round(float(acc),   4),
        }
    return result


def _print_summary(res_a: dict, res_b: dict) -> str:
    lines = []
    lines.append("=" * 60)
    lines.append("KAYABASA -- Features-Only Ablation Summary")
    lines.append("=" * 60)
    lines.append(
        f"{'Config':<12} {'Macro-F1':>10} {'+/-':>4} {'Accuracy':>10} {'+/-':>4}"
    )
    lines.append("-" * 44)
    for r in (res_a, res_b):
        lines.append(
            f"{r['config']:<12} {r['mean_macro_f1']:>10.4f} {r['std_macro_f1']:>8.4f}"
            f" {r['mean_accuracy']:>10.4f} {r['std_accuracy']:>8.4f}"

        )
    lines.append("")
    lines.append("Per-language Macro-F1 (out-of-fold, all folds combined):")
    lines.append(f"{'Language':<14} {'Config A':>10} {'Config B':>10}")
    lines.append("-" * 36)
    langs = sorted(set(res_a["per_language"]) | set(res_b["per_language"]))
    for lang in langs:
        a = res_a["per_language"].get(lang, {}).get("macro_f1", "-")
        b = res_b["per_language"].get(lang, {}).get("macro_f1", "-")
        a_str = f"{a:.4f}" if isinstance(a, float) else str(a)
        b_str = f"{b:.4f}" if isinstance(b, float) else str(b)
        lines.append(f"{lang:<14} {a_str:>10} {b_str:>10}")
    lines.append("")
    delta = res_b["mean_macro_f1"] - res_a["mean_macro_f1"]
    lines.append(
        f"Denoising impact (B - A): Delta Macro-F1 = {delta:+.4f}"
    )
    threshold = "CONFIRMED (>= 0.03)" if delta >= 0.03 else "below 0.03 threshold"
    lines.append(f"Thesis denoising threshold (S3.1.5): {threshold}")
    return "\n".join(lines)


# ===========================================================================
# Main
# ===========================================================================

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ── Load fold indices ─────────────────────────────────────────────────
    if not os.path.exists(FOLD_PKL):
        print(f"ERROR: fold_indices.pkl not found at {FOLD_PKL}")
        print("Run:  cd ../data-cleaning-repo-main && python split_datasets.py")
        sys.exit(1)
    with open(FOLD_PKL, "rb") as f:
        fold_indices = pickle.load(f)
    hr_index = pd.read_csv(HR_INDEX_CSV)
    print(f"Loaded {len(fold_indices)}-fold splits · "
          f"{len(hr_index)} high-resource docs")

    # ── Config B: Denoised features (the paper-aligned pipeline) ─────────
    if not os.path.exists(DENOISED_CORPUS):
        print(f"ERROR: Denoised corpus not found at {DENOISED_CORPUS}")
        print("Run:  cd ../data-cleaning-repo-main && python normalize_datasets.py")
        sys.exit(1)

    X_clean = _extract(DENOISED_CORPUS, label="Config B — DENOISED")
    res_b   = _run_cv(X_clean, fold_indices, hr_index, config_name="B (Denoised)")

    # Save Config B feature CSV (14 columns)
    feat_out = os.path.join(OUTPUT_DIR, "all_features.csv")
    X_clean.to_csv(feat_out, index=False)
    print(f"\n✓ Feature matrix saved → {feat_out}")

    # ── Config A: Noisy features ──────────────────────────────────────────
    if not os.path.exists(NOISY_CORPUS):
        print(f"\n[Config A] Noisy corpus not found at {NOISY_CORPUS}")
        print("  Skipping Config A (noisy baseline).")
        print("  To run Config A, produce output/all_languages_raw.txt from")
        print("  the data-cleaning pipeline (raw text before normalization).")
        res_a = None
    else:
        X_noisy = _extract(NOISY_CORPUS, label="Config A — NOISY")
        res_a   = _run_cv(X_noisy, fold_indices, hr_index, config_name="A (Noisy)")

    # ── Save results ──────────────────────────────────────────────────────
    json_b = os.path.join(OUTPUT_DIR, "results_config_B.json")
    with open(json_b, "w", encoding="utf-8") as f:
        json.dump(res_b, f, indent=2)
    print(f"\n✓ Config B results saved → {json_b}")

    if res_a:
        json_a = os.path.join(OUTPUT_DIR, "results_config_A.json")
        with open(json_a, "w", encoding="utf-8") as f:
            json.dump(res_a, f, indent=2)
        print(f"✓ Config A results saved → {json_a}")

        summary = _print_summary(res_a, res_b)
        summary_path = os.path.join(OUTPUT_DIR, "summary_features.txt")
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write(summary)
        print(f"✓ Summary saved → {summary_path}")
        print("\n" + summary)
    else:
        # Print Config B alone
        print(f"\n" + "=" * 60)
        print("KAYABASA -- Config B (Denoised Features) Results")
        print("=" * 60)
        print(f"Mean Macro-F1 : {res_b['mean_macro_f1']:.4f} +/- "
              f"{res_b['std_macro_f1']:.4f}")
        print(f"Mean Accuracy : {res_b['mean_accuracy']:.4f} +/- "
              f"{res_b['std_accuracy']:.4f}")

        print("\nPer-language Macro-F1:")
        for lang, m in res_b["per_language"].items():
            print(f"  {lang:<14} F1={m['macro_f1']:.4f}  Acc={m['accuracy']:.4f}")
        print("\nPer-fold Macro-F1:")
        for fr in res_b["folds"]:
            print(f"  Fold {fr['fold']}: {fr['macro_f1']:.4f}")


if __name__ == "__main__":
    main()
