# -*- coding: utf-8 -*-
"""ACL2023 - Extract_Embeddings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fIPw6yZdGWKAm7D9MDZ2zCA0ziL4SgkE
"""

from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
from pathlib import Path

project_dir = Path(__file__).resolve().parent.parent
clean_dir = project_dir / "clean"
output_dir = Path(__file__).resolve().parent / "generated"
input_files = {
    "bik": clean_dir / "bik_all_clean.txt",
    "ceb": clean_dir / "ceb_all_clean.txt",
    "tag": clean_dir / "tag_all_clean.txt",
}


def load_contents(input_path):
    contents = []
    with input_path.open("r", encoding="utf-8", errors="ignore") as file:
        for line_number, line in enumerate(file, start=1):
            parsed_text = line.rstrip("\n").split(",", 2)
            if len(parsed_text) < 3:
                print(f"Skipping malformed line {line_number} in {input_path.name}")
                continue
            contents.append(parsed_text[2].strip())
    return contents

def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, 1)
    sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)
    return sum_embeddings / sum_mask

tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-uncased")
model = AutoModel.from_pretrained("bert-base-multilingual-uncased")

output_dir.mkdir(exist_ok=True)

for language, input_path in input_files.items():
    contents = load_contents(input_path)
    if not contents:
        print(f"No usable text found in {input_path}")
        continue

    encoded_input = tokenizer(
        contents,
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt",
    )

    with torch.no_grad():
        model_output = model(**encoded_input)

    sentence_embeddings = mean_pooling(
        model_output, encoded_input["attention_mask"]
    )
    sentence_embeddings_np = sentence_embeddings.numpy()
    output_path = output_dir / f"{language}_mbert_features.csv"
    np.savetxt(output_path, sentence_embeddings_np, delimiter=",")
    print(f"Saved {len(contents)} embeddings to {output_path}")